# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: telegrambot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/azyablitsev/Documents/projects/msai/01 sem/01 SoftwareDev/10 bot/meeting_arrangement_bot/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
